# References
# https://github.com/paularmstrong/build-tracker/tree/main/.github/workflows
name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
  pull_request:
    branches:
      - main
    paths:
        - 'website/**'

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install -g yarn
      - name: Install packages
        working-directory: ./website
        run: yarn install
      - name: Build website
        working-directory: ./website
        run: yarn build
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build